version: '3.8'

services:
  php-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
    networks:
      - backend-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cutfill_db
      MYSQL_USER: deon
      MYSQL_PASSWORD: "12345"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_USER: deon
      MYSQL_PASSWORD: "12345"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend-net

volumes:
  db_data:

networks:
  backend-net:
    driver: bridge
